const express = require('express');
const app = express();
const cors = require('cors');
const port = 4000;

app.use(cors());


// const cities = [
//     { name: 'Abidjan' },
//     { name: 'Abu Dhabi' },
//     { name: 'Abuja' },
//     { name: 'Accra' },
//     { name: 'Addis Ababa' },
//     { name: 'Ahmedabad' },
//     { name: 'Aleppo' },
//     { name: 'Alexandria' },
//     { name: 'Algiers' },
//     { name: 'Almaty' },
//     { name: 'Amman' },
//     { name: 'Amsterdam' },
//     { name: 'Anchorage' },
//     { name: 'Andorra la Vella' },
//     { name: 'Ankara' },
//     { name: 'Antananarivo' },
//     { name: 'Apia' },
//     { name: 'Arnold' },
//     { name: 'Ashgabat' },
//     { name: 'Asmara' },
//     { name: 'Asuncion' },
//     { name: 'Athens' },
//     { name: 'Auckland' },
//     { name: 'Avarua' },
//     { name: 'Baghdad' },
//     { name: 'Baku' },
//     { name: 'Bamako' },
//     { name: 'Banda Aceh' },
//     { name: 'Bandar Seri Begawan' },
//     { name: 'Bandung' },
//     { name: 'Bangkok' },
//     { name: 'Bangui' },
//     { name: 'Banjul' },
//     { name: 'Barcelona' },
//     { name: 'Barranquilla' },
//     { name: 'Basrah' },
//     { name: 'Basse-Terre' },
//     { name: 'Basseterre' },
//     { name: 'Beijing' },
//     { name: 'Beirut' },
//     { name: 'Bekasi' },
//     { name: 'Belem' },
//     { name: 'Belgrade' },
//     { name: 'Belmopan' },
//     { name: 'Belo Horizonte' },
//     { name: 'Bengaluru' },
//     { name: 'Berlin' },
//     { name: 'Bern' },
//     { name: 'Bishkek' },
//     { name: 'Bissau' },
//     { name: 'Bogota' },
//     { name: 'Brasilia' },
//     { name: 'Bratislava' },
//     { name: 'Brazzaville' },
//     { name: 'Bridgetown' },
//     { name: 'Brisbane' },
//     { name: 'Brussels' },
//     { name: 'Bucharest' },
//     { name: 'Budapest' },
//     { name: 'Buenos Aires' },
//     { name: 'Bujumbura' },
//     { name: 'Bursa' },
//     { name: 'Busan' },
//     { name: 'Cairo' },
//     { name: 'Cali' },
//     { name: 'Caloocan' },
//     { name: 'Camayenne' },
//     { name: 'Canberra' },
//     { name: 'Cape Town' },
//     { name: 'Caracas' },
//     { name: 'Casablanca' },
//     { name: 'Castries' },
//     { name: 'Cayenne' },
//     { name: 'Charlotte Amalie' },
//     { name: 'Chengdu' },
//     { name: 'Chicago' },
//     { name: 'Chisinau' },
//     { name: 'Chittagong' },
//     { name: 'Chongqing' },
//     { name: 'Colombo' },
//     { name: 'Conakry' },
//     { name: 'Copenhagen' },
//     { name: 'Cordoba' },
//     { name: 'Curitiba' },
//     { name: 'Daegu' },
//     { name: 'Daejeon' },
//     { name: 'Dakar' },
//     { name: 'Dallas' },
//     { name: 'Damascus' },
//     { name: 'Dar es Salaam' },
//     { name: 'Delhi' },
//     { name: 'Denver' },
//     { name: 'Dhaka' },
//     { name: 'Dili' },
//     { name: 'Djibouti' },
//     { name: 'Dodoma' },
//     { name: 'Doha' },
//     { name: 'Dongguan' },
//     { name: 'Douala' },
//     { name: 'Douglas' },
//     { name: 'Dubai' },
//     { name: 'Dublin' },
//     { name: 'Durban' },
//     { name: 'Dushanbe' },
//     { name: 'Faisalabad' },
//     { name: 'Fort-de-France' },
//     { name: 'Fortaleza' },
//     { name: 'Freetown' },
//     { name: 'Fukuoka' },
//     { name: 'Funafuti' },
//     { name: 'Gaborone' },
//     { name: 'George Town' },
//     { name: 'Georgetown' },
//     { name: 'Gibraltar' },
//     { name: 'Gitega' },
//     { name: 'Giza' },
//     { name: 'Guadalajara' },
//     { name: 'Guangzhou' },
//     { name: 'Guatemala City' },
//     { name: 'Guayaquil' },
//     { name: 'Gujranwala' },
//     { name: 'Gustavia' },
//     { name: 'Gwangju' },
//     { name: 'Hamburg' },
//     { name: 'Hanoi' },
//     { name: 'Harare' },
//     { name: 'Havana' },
//     { name: 'Helsinki' },
//     { name: 'Ho Chi Minh City' },
//     { name: 'Hong Kong' },
//     { name: 'Honiara' },
//     { name: 'Honolulu' },
//     { name: 'Houston' },
//     { name: 'Hyderabad' },
//     { name: 'Hyderabad' },
//     { name: 'Ibadan' },
//     { name: 'Incheon' },
//     { name: 'Isfahan' },
//     { name: 'Islamabad' },
//     { name: 'Istanbul' },
//     { name: 'Izmir' },
//     { name: 'Jaipur' },
//     { name: 'Jakarta' },
//     { name: 'Jeddah' },
//     { name: 'Jerusalem' },
//     { name: 'Johannesburg' },
//     { name: 'Juarez' },
//     { name: 'Juba' },
//     { name: 'Kabul' },
//     { name: 'Kaduna' },
//     { name: 'Kampala' },
//     { name: 'Kano' },
//     { name: 'Kanpur' },
//     { name: 'Kaohsiung' },
//     { name: 'Karachi' },
//     { name: 'Karaj' },
//     { name: 'Kathmandu' },
//     { name: 'Kawasaki' },
//     { name: 'Kharkiv' },
//     { name: 'Khartoum' },
//     { name: 'Khulna' },
//     { name: 'Kigali' },
//     { name: 'Kingsburg' },
//     { name: 'Kingston' },
//     { name: 'Kingstown' },
//     { name: 'Kinshasa' },
//     { name: 'Kobe' },
//     { name: 'Kolkata' },
//     { name: 'Kota Bharu' },
//     { name: 'Kowloon' },
//     { name: 'Kuala Lumpur' },
//     { name: 'Kumasi' },
//     { name: 'Kuwait' },
//     { name: 'Kyiv' },
//     { name: 'Kyoto' },
//     { name: 'La Paz' },
//     { name: 'Lagos' },
//     { name: 'Lahore' },
//     { name: 'Libreville' },
//     { name: 'Lilongwe' },
//     { name: 'Lima' },
//     { name: 'Lisbon' },
//     { name: 'Ljubljana' },
//     { name: 'Lome' },
//     { name: 'London' },
//     { name: 'Los Angeles' },
//     { name: 'Luanda' },
//     { name: 'Lubumbashi' },
//     { name: 'Lusaka' },
//     { name: 'Luxembourg' },
//     { name: 'Macau' },
//     { name: 'Madrid' },
//     { name: 'Majuro' },
//     { name: 'Makassar' },
//     { name: 'Malabo' },
//     { name: 'Male' },
//     { name: 'Mamoudzou' },
//     { name: 'Managua' },
//     { name: 'Manama' },
//     { name: 'Manaus' },
//     { name: 'Manila' },
//     { name: 'Maputo' },
//     { name: 'Maracaibo' },
//     { name: 'Maracay' },
//     { name: 'Mariehamn' },
//     { name: 'Marigot' },
//     { name: 'Maseru' },
//     { name: 'Mashhad' },
//     { name: 'Mbabane' },
//     { name: 'Mecca' },
//     { name: 'Medan' },
//     { name: 'Medellin' },
//     { name: 'Medina' },
//     { name: 'Melbourne' },
//     { name: 'Mexico City' },
//     { name: 'Miami' },
//     { name: 'Minsk' },
//     { name: 'Mogadishu' },
//     { name: 'Monaco' },
//     { name: 'Monrovia' },
//     { name: 'Montevideo' },
//     { name: 'Montreal' },
//     { name: 'Moroni' },
//     { name: 'Moscow' },
//     { name: 'Mosul' },
//     { name: 'Multan' },
//     { name: 'Mumbai' },
//     { name: 'Muscat' },
//     { name: 'Nagoya' },
//     { name: 'Nairobi' },
//     { name: 'Nanchong' },
//     { name: 'Nanjing' },
//     { name: 'Nassau' },
//     { name: 'Nay Pyi Taw' },
//     { name: 'New York' },
//     { name: 'Niamey' },
//     { name: 'Nicosia' },
//     { name: 'Nouakchott' },
//     { name: 'Noumea' },
//     { name: 'Novosibirsk' },
//     { name: 'Nur-Sultan' },
//     { name: 'Nuuk' },
//     { name: 'Oranjestad' },
//     { name: 'Osaka' },
//     { name: 'Oslo' },
//     { name: 'Ottawa' },
//     { name: 'Ouagadougou' },
//     { name: 'Pago Pago' },
//     { name: 'Palembang' },
//     { name: 'Palo Alto' },
//     { name: 'Panama' },
//     { name: 'Papeete' },
//     { name: 'Paramaribo' },
//     { name: 'Paris' },
//     { name: 'Perth' },
//     { name: 'Philadelphia' },
//     { name: 'Phnom Penh' },
//     { name: 'Phoenix' },
//     { name: 'Podgorica' },
//     { name: 'Port Louis' },
//     { name: 'Port Moresby' },
//     { name: 'Port of Spain' },
//     { name: 'Port-Vila' },
//     { name: 'Port-au-Prince' },
//     { name: 'Porto Alegre' },
//     { name: 'Porto-Novo' },
//     { name: 'Prague' },
//     { name: 'Praia' },
//     { name: 'Pretoria' },
//     { name: 'Pristina' },
//     { name: 'Puebla' },
//     { name: 'Pune' },
//     { name: 'Pyongyang' },
//     { name: 'Quezon City' },
//     { name: 'Quito' },
//     { name: 'Rabat' },
//     { name: 'Rawalpindi' },
//     { name: 'Recife' },
//     { name: 'Reykjavik' },
//     { name: 'Riga' },
//     { name: 'Rio de Janeiro' },
//     { name: 'Riyadh' },
//     { name: 'Road Town' },
//     { name: 'Rome' },
//     { name: 'Roseau' },
//     { name: 'Saint Helier' },
//     { name: 'Saint Peter Port' },
//     { name: 'Saint Petersburg' },
//     { name: 'Saint-Denis' },
//     { name: 'Saint-Pierre' },
//     { name: 'Saipan' },
//     { name: 'Salvador' },
//     { name: 'San Antonio' },
//     { name: 'San Diego' },
//     { name: 'San Francisco' },
//     { name: 'San Jose' },
//     { name: 'San Juan' },
//     { name: 'San Marino' },
//     { name: 'San Salvador' },
//     { name: 'Sanaa' },
//     { name: 'Santa Cruz de la Sierra' },
//     { name: 'Santiago' },
//     { name: 'Santo Domingo' },
//     { name: 'Sao Paulo' },
//     { name: 'Sao Tome' },
//     { name: 'Sapporo' },
//     { name: 'Sarajevo' },
//     { name: 'Seattle' },
//     { name: 'Semarang' },
//     { name: 'Seoul' },
//     { name: 'Shanghai' },
//     { name: 'Sharjah' },
//     { name: 'Shenzhen' },
//     { name: 'Singapore' },
//     { name: 'Skopje' },
//     { name: 'Sofia' },
//     // { name: 'South Tangerang' },
//     { name: 'Soweto' },
//     { name: 'Stockholm' },
//     { name: 'Sucre' },
//     { name: 'Surabaya' },
//     { name: 'Surat' },
//     { name: 'Suva' },
//     { name: 'Sydney' },
//     { name: 'Tabriz' },
//     { name: 'Taipei' },
//     { name: 'Tallinn' },
//     { name: 'Tangerang' },
//     { name: 'Tarawa' },
//     { name: 'Tashkent' },
//     { name: 'Tbilisi' },
//     { name: 'Tegucigalpa' },
//     { name: 'Tehran' },
//     { name: 'Tel Aviv' },
//     { name: 'Thimphu' },
//     { name: 'Tianjin' },
//     { name: 'Tijuana' },
//     { name: 'Tirana' },
//     { name: 'Tokyo' },
//     { name: 'Toronto' },
//     { name: 'Torshavn' },
//     { name: 'Tripoli' },
//     { name: 'Tunis' },
//     { name: 'Ulan Bator' },
//     { name: 'Vaduz' },
//     { name: 'Valencia' },
//     { name: 'Valletta' },
//     { name: 'Vancouver' },
//     { name: 'Victoria' },
//     { name: 'Vienna' },
//     { name: 'Vientiane' },
//     { name: 'Vilnius' },
//     { name: 'Warsaw' },
//     { name: 'Washington' },
//     { name: 'Wellington' },
//     { name: 'Willemstad' },
//     { name: 'Windhoek' },
//     { name: 'Wuhan' },
//     { name: 'Yamoussoukro' },
//     { name: 'Yangon' },
//     { name: 'Yaounde' },
//     { name: 'Yekaterinburg' },
//     { name: 'Yerevan' },
//     { name: 'Yokohama' },
//     { name: 'Zagreb' },
// ];


 const cities = [
        { name: 'New York', coords: { lat: 40.7128, lon: -74.0060 } },
        { name: 'London', coords: { lat: 51.509865, lon: -0.118092 } },
        { name: 'Tokyo', coords: { lat: 35.6895, lon: 139.6917 } },
        { name: 'Beijing', coords: { lat: 39.9042, lon: 116.4074 } },
        { name: 'Sydney', coords: { lat: -33.8688, lon: 151.2093 } },
        { name: 'Cape Town', coords: { lat: -33.9249, lon: 18.4241 } },
        { name: 'Rio de Janeiro', coords: { lat: -22.9083, lon: -43.1964 } },
        { name: 'Delhi', coords: { lat: 28.6139, lon: 77.2090 } },
        { name: 'Gharaunda', coords: { lat: 29.5404, lon: 76.9784 } },
        { name: 'Mumbai', coords: { lat: 19.0760, lon: 72.8777 } },
        { name: 'Chennai', coords: { lat: 13.0827, lon: 80.2707 } },
        { name: 'Kolkata', coords: { lat: 22.5726, lon: 88.3639 } },
        { name: 'Bangalore', coords: { lat: 12.9716, lon: 77.5946 } },
        { name: 'Hyderabad', coords: { lat: 17.3850, lon: 78.4867 } },
        { name: 'Ahmedabad', coords: { lat: 23.0225, lon: 72.5714 } },
        { name: 'Pune', coords: { lat: 18.5204, lon: 73.8567 } },
        { name: 'Jaipur', coords: { lat: 26.9124, lon: 75.7873 } },
        { name: 'Lucknow', coords: { lat: 26.8467, lon: 80.9462 } },
        { name: 'Moscow', coords: { lat: 55.7558, lon: 37.6176 } },
        { name: 'Paris', coords: { lat: 48.8566, lon: 2.3522 } },
        { name: 'Berlin', coords: { lat: 52.5200, lon: 13.4050 } },
        { name: 'Rome', coords: { lat: 41.9028, lon: 12.4964 } },
        { name: 'Istanbul', coords: { lat: 41.0082, lon: 28.9784 } },
        { name: 'Shanghai', coords: { lat: 31.2304, lon: 121.4737 } },
        { name: 'Toronto', coords: { lat: 43.6532, lon: -79.3832 } },
        { name: 'Los Angeles', coords: { lat: 34.0522, lon: -118.2437 } },
        { name: 'Toronto', coords: { lat: 43.651070, lon: -79.347015 } }

    ];


app.get('/cities', (req, res) => {
    res.json(cities);
});

app.listen(port, () => {
    console.log(`Server is running at http://localhost:${port}`);
});
